export const LOAD_REPOSITORIES_SUCCESS = 'LOAD_REPOSITORIES_SUCCESS';
export const ADD_REPOSITORY_TO_FAVORITES = 'ADD_REPOSITORY_TO_FAVORITES';
export const REMOVE_REPOSITORY_FROM_FAVORITES =
  'REMOVE_REPOSITORY_FROM_FAVORITES';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
